name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export secret to env
        run: echo "MY_SECRET=${{ secrets.MY_SECRET }}" 

  
